name: oximapp_v2
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  path_provider:

  cupertino_icons: ^1.0.2
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1
  provider: ^6.0.5
  auto_route: ^7.7.0
  auto_route_generator: ^7.2.0
  get_it: ^7.6.0
  injectable: ^2.1.2
  l: ^4.0.2
  flutter_native_splash: ^2.3.1
  hive: ^2.2.3
  hive_generator: ^2.0.0
  hive_flutter: ^1.1.0
  slang: ^3.23.0
  slang_flutter: ^3.23.0
  google_fonts: ^6.1.0
  gap: ^3.0.1
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  image_picker: ^1.0.4
  expandable: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  slang_build_runner: ^3.23.0
  freezed: ^2.3.5
  injectable_generator: ^2.1.6
  isar_generator: ^3.1.0+1

flutter:
  uses-material-design: true
